# $Id: Makefile,v 5.2 2008/01/30 23:51:38 ksb Exp $
#
# msrc 2008 makefile for mk-lib/type

SOURCE=	Makefile Makefile.host \
	b c d p s
INTO=	/usr/src/local/lib/mk/type

${SOURCE}:
	co -q $@

__msrc: ${SOURCE}
