# $Id: Makefile,v 5.3 2008/01/30 23:51:38 ksb Exp $
#
# msrc 2008 makefile for mk-lib/m

SOURCE=	Makefile Makefile.host README mkcat.host \
	clean_ compile display info run
INTO=	/usr/src/local/lib/mk/m

${SOURCE}:
	co -q $@

__msrc: ${SOURCE}
