# $Id: Makefile,v 5.4 2008/08/12 16:44:14 ksb Exp $
#
# msrc 2008 makefile for mk-lib/file

SOURCE=	Makefile Makefile.host \
	calendar distfile_ gmon.out kernel.conf makefile_ msrc_ tclIndex \
	valid zmagic
INTO=	/usr/src/local/lib/mk/file

${SOURCE}:
	co -q $@

__msrc: ${SOURCE}
