# $Id: Makefile,v 5.2 2008/01/30 23:51:38 ksb Exp $
#
# msrc 2008 makefile for mk-lib/pre

SOURCE=	Makefile Makefile.host \
	C MW W Z a au bshlf cpio dir dvi ln nib o out patch \
	tar tex texi uu z zoo
INTO=	/usr/src/local/lib/mk/pre

${SOURCE}:
	co -q $@

__msrc: ${SOURCE}
