# $Id: Makefile,v 5.4 2008/10/26 16:33:19 ksb Exp $
# msrc 2008 makefile for mk-lib/is, msrc 2008
INTO=	/usr/src/local/lib/mk/is

SOURCE=	Makefile Makefile.host TODO \
	bzip2 comma-v compact dvi gzip latex new-compact no-extender \
	sqeeze tex texinfo

${SOURCE}:
	co -q $@

__msrc: ${SOURCE}
