# $Id: Makefile,v 5.3 2008/10/26 16:49:07 ksb Exp $
#
# msrc 2008 makefile for mk-lib/map

SOURCE=	Makefile Makefile.host TODO \
	au-encoding au-width cpio dirs magic post pre
INTO=	/usr/src/local/lib/mk/map

${SOURCE}:
	co -q $@

__msrc: ${SOURCE}
