# $Id: Makefile,v 5.4 2008/04/05 18:28:38 ksb Exp $
#
# msrc 2008 makefile for mk-lib/dot

GEN=	1 c f man p s
SOURCE=	Makefile Makefile.host 1.host c.host f.host man.host \
	p.host s.host \
	C bcpl e el h html hxmd int l m m4 mk \
	ph pl ps r sh shar t xbm y
INTO=	/usr/src/local/lib/mk/dot

${SOURCE}:
	co -q $@

__msrc: ${SOURCE}
